### ISSUE TITLE
Flaky testcase in OtelTraceSource

### ISSUE THREAD

**Issue by chenqi0805** [opendistro-for-elasticsearch/data-prepper#221]
Occasionally found in CI:
```
> Task :data-prepper-plugins:otel-trace-source:test

OTelTraceSourceTest > testBufferFull() FAILED
    io.grpc.StatusRuntimeException at OTelTraceSourceTest.java:71


7 tests completed, 1 failed
> Task :data-prepper-plugins:otel-trace-source:test FAILED
```
@AustinTag has also seen this in CI on PR.

**Comment by kowshikn** [comment]
Is this after the latest fix from @AustinTag ?

**Comment by sshivanii** [comment]
Encountered the same on my PR.

**Comment by chenqi0805** [comment]
It might be due to UnprocessedRequestException or Request timeout exception in the armeria client. As a workaround, I will try adding retry to see if it stabilizes.

**Comment by chenqi0805** [comment]
adding retry does not prevent it. Need to investigate further.

**Comment by chenqi0805** [comment]
Was just able to get a full Traceback:

```
2020-12-17T21:34:15.6198776Z 2020-12-17T21:34:15.593+0000 [DEBUG] [TestEventLogger] OTelTraceSourceTest > testBufferFull() FAILED
2020-12-17T21:34:15.6200032Z 2020-12-17T21:34:15.594+0000 [DEBUG] [TestEventLogger]     io.grpc.StatusRuntimeException: CANCELLED
2020-12-17T21:34:15.6201785Z 2020-12-17T21:34:15.594+0000 [DEBUG] [TestEventLogger]         at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
2020-12-17T21:34:15.6203663Z 2020-12-17T21:34:15.594+0000 [DEBUG] [TestEventLogger]         at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
2020-12-17T21:34:15.6205770Z 2020-12-17T21:34:15.594+0000 [DEBUG] [TestEventLogger]         at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
2020-12-17T21:34:15.6208412Z 2020-12-17T21:34:15.594+0000 [DEBUG] [TestEventLogger]         at io.opentelemetry.proto.collector.trace.v1.TraceServiceGrpc$TraceServiceBlockingStub.export(TraceServiceGrpc.java:201)
2020-12-17T21:34:15.6212231Z 2020-12-17T21:34:15.594+0000 [DEBUG] [TestEventLogger]         at com.amazon.dataprepper.plugins.source.oteltrace.OTelTraceSourceTest.testBufferFull(OTelTraceSourceTest.java:80)
2020-12-17T21:34:15.6215597Z 2020-12-17T21:34:15.594+0000 [DEBUG] [TestEventLogger]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-12-17T21:34:15.6218163Z 2020-12-17T21:34:15.594+0000 [DEBUG] [TestEventLogger]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-12-17T21:34:15.6221132Z 2020-12-17T21:34:15.594+0000 [DEBUG] [TestEventLogger]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-12-17T21:34:15.6223403Z 2020-12-17T21:34:15.594+0000 [DEBUG] [TestEventLogger]         at java.base/java.lang.reflect.Method.invoke(Method.java:564)
2020-12-17T21:34:15.6225619Z 2020-12-17T21:34:15.594+0000 [DEBUG] [TestEventLogger]         at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
2020-12-17T21:34:15.6228365Z 2020-12-17T21:34:15.594+0000 [DEBUG] [TestEventLogger]         at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
2020-12-17T21:34:15.6231697Z 2020-12-17T21:34:15.594+0000 [DEBUG] [TestEventLogger]         at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
2020-12-17T21:34:15.6234956Z 2020-12-17T21:34:15.594+0000 [DEBUG] [TestEventLogger]         at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
2020-12-17T21:34:15.6238255Z 2020-12-17T21:34:15.594+0000 [DEBUG] [TestEventLogger]         at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
2020-12-17T21:34:15.6241835Z 2020-12-17T21:34:15.594+0000 [DEBUG] [TestEventLogger]         at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
2020-12-17T21:34:15.6245167Z 2020-12-17T21:34:15.594+0000 [DEBUG] [TestEventLogger]         at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
2020-12-17T21:34:15.6248136Z 2020-12-17T21:34:15.594+0000 [DEBUG] [TestEventLogger]         at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
2020-12-17T21:34:15.6251392Z 2020-12-17T21:34:15.594+0000 [DEBUG] [TestEventLogger]         at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
2020-12-17T21:34:15.6255019Z 2020-12-17T21:34:15.594+0000 [DEBUG] [TestEventLogger]         at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
2020-12-17T21:34:15.6258846Z 2020-12-17T21:34:15.594+0000 [DEBUG] [TestEventLogger]         at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
2020-12-17T21:34:15.6262661Z 2020-12-17T21:34:15.594+0000 [DEBUG] [TestEventLogger]         at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
2020-12-17T21:34:15.6265823Z 2020-12-17T21:34:15.594+0000 [DEBUG] [TestEventLogger]         at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
2020-12-17T21:34:15.6268576Z 2020-12-17T21:34:15.594+0000 [DEBUG] [TestEventLogger]         at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
2020-12-17T21:34:15.6334585Z 2020-12-17T21:34:15.594+0000 [DEBUG] [TestEventLogger]         at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
2020-12-17T21:34:15.6338811Z 2020-12-17T21:34:15.594+0000 [DEBUG] [TestEventLogger]         at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-12-17T21:34:15.6342678Z 2020-12-17T21:34:15.594+0000 [DEBUG] [TestEventLogger]         at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
2020-12-17T21:34:15.6346514Z 2020-12-17T21:34:15.594+0000 [DEBUG] [TestEventLogger]         at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
2020-12-17T21:34:15.6350021Z 2020-12-17T21:34:15.594+0000 [DEBUG] [TestEventLogger]         at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
2020-12-17T21:34:15.6353587Z 2020-12-17T21:34:15.594+0000 [DEBUG] [TestEventLogger]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
2020-12-17T21:34:15.6357270Z 2020-12-17T21:34:15.594+0000 [DEBUG] [TestEventLogger]         at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-12-17T21:34:15.6360733Z 2020-12-17T21:34:15.594+0000 [DEBUG] [TestEventLogger]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
2020-12-17T21:34:15.6363576Z 2020-12-17T21:34:15.594+0000 [DEBUG] [TestEventLogger]         at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2020-12-17T21:34:15.6366410Z 2020-12-17T21:34:15.594+0000 [DEBUG] [TestEventLogger]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
2020-12-17T21:34:15.6369855Z 2020-12-17T21:34:15.594+0000 [DEBUG] [TestEventLogger]         at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-12-17T21:34:15.6373531Z 2020-12-17T21:34:15.594+0000 [DEBUG] [TestEventLogger]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
2020-12-17T21:34:15.6376973Z 2020-12-17T21:34:15.594+0000 [DEBUG] [TestEventLogger]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
2020-12-17T21:34:15.6379197Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2020-12-17T21:34:15.6406207Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
2020-12-17T21:34:15.6411388Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
2020-12-17T21:34:15.6414813Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-12-17T21:34:15.6418246Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
2020-12-17T21:34:15.6421124Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2020-12-17T21:34:15.6428640Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
2020-12-17T21:34:15.6441219Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-12-17T21:34:15.6448180Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
2020-12-17T21:34:15.6451702Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
2020-12-17T21:34:15.6453943Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2020-12-17T21:34:15.6460953Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
2020-12-17T21:34:15.6466037Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
2020-12-17T21:34:15.6469659Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-12-17T21:34:15.6473520Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
2020-12-17T21:34:15.6476393Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2020-12-17T21:34:15.6479252Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
2020-12-17T21:34:15.6482930Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2020-12-17T21:34:15.6486861Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
2020-12-17T21:34:15.6490322Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
2020-12-17T21:34:15.6494949Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
2020-12-17T21:34:15.6500069Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
2020-12-17T21:34:15.6504156Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
2020-12-17T21:34:15.6507412Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
2020-12-17T21:34:15.6509974Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
2020-12-17T21:34:15.6513159Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
2020-12-17T21:34:15.6516116Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
2020-12-17T21:34:15.6518701Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
2020-12-17T21:34:15.6523196Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
2020-12-17T21:34:15.6529000Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
2020-12-17T21:34:15.6534269Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
2020-12-17T21:34:15.6538451Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
2020-12-17T21:34:15.6541287Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-12-17T21:34:15.6543841Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-12-17T21:34:15.6546844Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-12-17T21:34:15.6549095Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at java.base/java.lang.reflect.Method.invoke(Method.java:564)
2020-12-17T21:34:15.6551157Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
2020-12-17T21:34:15.6553887Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
2020-12-17T21:34:15.6561537Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
2020-12-17T21:34:15.6564988Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
2020-12-17T21:34:15.6567098Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at com.sun.proxy.$Proxy5.stop(Unknown Source)
2020-12-17T21:34:15.6568975Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:133)
2020-12-17T21:34:15.6571470Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-12-17T21:34:15.6574678Z 2020-12-17T21:34:15.595+0000 [DEBUG] [TestEventLogger]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-12-17T21:34:15.6577629Z 2020-12-17T21:34:15.596+0000 [DEBUG] [TestEventLogger]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-12-17T21:34:15.6579881Z 2020-12-17T21:34:15.596+0000 [DEBUG] [TestEventLogger]         at java.base/java.lang.reflect.Method.invoke(Method.java:564)
2020-12-17T21:34:15.6581964Z 2020-12-17T21:34:15.596+0000 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
2020-12-17T21:34:15.6584940Z 2020-12-17T21:34:15.596+0000 [DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
2020-12-17T21:34:15.6588787Z 2020-12-17T21:34:15.596+0000 [DEBUG] [TestEventLogger]         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
2020-12-17T21:34:15.6605487Z 2020-12-17T21:34:15.596+0000 [DEBUG] [TestEventLogger]         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
2020-12-17T21:34:15.6611457Z 2020-12-17T21:34:15.596+0000 [DEBUG] [TestEventLogger]         at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
2020-12-17T21:34:15.6613986Z 2020-12-17T21:34:15.596+0000 [DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
2020-12-17T21:34:15.6616939Z 2020-12-17T21:34:15.596+0000 [DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
2020-12-17T21:34:15.6619454Z 2020-12-17T21:34:15.596+0000 [DEBUG] [TestEventLogger]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
2020-12-17T21:34:15.6621711Z 2020-12-17T21:34:15.596+0000 [DEBUG] [TestEventLogger]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
2020-12-17T21:34:15.6627510Z 2020-12-17T21:34:15.596+0000 [DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
2020-12-17T21:34:15.6631659Z 2020-12-17T21:34:15.596+0000 [DEBUG] [TestEventLogger]         at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by kowshikn** [comment]
@chenqi0805 Did this happen again?

**Comment by chenqi0805** [comment]
@kowshikn Occasionally. Usually pass in re-run

**Comment by wrijeff** [comment]
We'll need this fixed as we start to use automated dependency upgrade PRs (#314). The bot created 3 PRs today, 2 of which failed due to:
```
OTelTraceSourceTest > testBufferFull() FAILED
    io.grpc.StatusRuntimeException at OTelTraceSourceTest.java:109
```

**Comment by chenqi0805** [comment]
I have searched on google and stackoverflow and it is hard to see the root cause as cancellation can happen for a variety of reasons (network error, deadline exceeded). Not sure if increase the request timeout helps.

**Comment by wrijeff** [comment]
Appears to have been resolved by #323, will re-open if test begins to fail again

**Comment by chenqi0805** [comment]
Looks like it is still present as CI fails on https://github.com/opendistro-for-elasticsearch/data-prepper/pull/299 which only touches README
